-- Test SQL

--INSERT RECORDS INTO PLAYERS TABLE
INSERT INTO players VALUES ('Fred');
INSERT INTO players VALUES ('David');
INSERT INTO players VALUES ('James');
INSERT INTO players VALUES ('Harry');

--INSERT RECORDS INTO MATCHES TABLE
INSERT INTO matches VALUES (1,2);
INSERT INTO matches VALUES (3,4);


--  COUNT ALL RECORDS IN PLAYERS TABLE
SELECT count(*) FROM players;

